import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Game from "../game/Game";

const Home: NextPage = () => {
  const [hasStarted, setHasStarted] = useState(false);

  const start = () => setHasStarted(true);
  return (
    <>
      <Head>
        <title>Factorize or DIE</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-start p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Factorize or <span className="text-red-700">DIE</span>
        </h1>
        <div className="mt-4 flex h-full w-full flex-grow flex-col items-center justify-center">
          {hasStarted ? (
            <Game />
          ) : (
            <button
              onClick={start}
              className="mt-4 rounded bg-red-700 py-2 px-4 font-mono text-3xl font-bold text-white transition-colors hover:bg-red-600"
            >
              Start
            </button>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
